name: Goreleaser

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    tags: ["v*"]

jobs:
  tagger:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: write
    steps:
      - name: Create tag
        id: tag
        uses: actions/github-script@v6
        if: github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'release/')
        with:
          github-token: ${{ github.token }}
          script: |
            const tag = context.payload.pull_request.head.ref.replace("release/", "v")
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "refs/tags/" + tag,
              })
            } catch {
            }
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/" + tag,
              sha: context.payload.pull_request.merge_commit_sha,
            })
            return tag
          result-encoding: string
    outputs:
      tag: ${{ steps.tag.outputs.result }}

  get-tag:
    runs-on: ubuntu-latest
    if: success() || needs.tagger.result == 'skipped'
    needs:
      - tagger
    steps:
      - name: get pushed tag
        id: pushed
        if: needs.tagger.result != 'success'
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: get created tag
        id: created
        run: echo "::set-output name=tag::$TAG"
        if: needs.tagger.result == 'success'
        env:
          TAG: "${{ needs.tagger.outputs.tag }}"

      - name: combine tags
        id: combined
        run: echo "::set-output name=tag::$CREATED$PUSHED"
        env:
          CREATED: ${{ steps.created.outputs.tag }}
          PUSHED: ${{ steps.pushed.outputs.tag }}
    outputs:
      tag: ${{ steps.combined.outputs.tag }}

  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write # releases are in `contents`
      issues: write # for closing milestones
      packages: write
    if: success()
    needs:
      - get-tag
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ needs.get-tag.outputs.tag }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.CR_PAT }}
          TELEGRAM_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Generate schema.json
        run: ./dist/helmwave schema > schema.json
      - name: Upload schema.json
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "schema.json"
          update_latest_release: true

  docs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    needs:
      - get-tag
      - goreleaser
    steps:
      - name: Trigger helmwave/docs workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: "docs",
              workflow_id: "generate-new-version.yml",
              ref: "main",
              inputs: {
                tag: process.env.GITHUB_TAG,
              },
            })
        env:
          GITHUB_TAG: ${{ needs.get-tag.outputs.tag }}
